name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Auto-Fix Files and Directories
      run: |
        # إنشاء ملف package.json إذا لم يكن موجوداً
        if [ ! -f package.json ]; then
          echo '{"name": "my-app", "version": "1.0.0", "dependencies": {}}' > package.json
        fi
        # إنشاء مجلد www الأساسي
        mkdir -p www
        if [ ! -f www/index.html ]; then
          echo "<html><body><h1>App Ready</h1></body></html>" > www/index.html
        fi

    - name: Install Tools and Repair
      run: |
        npm install
        npm install @capacitor/cli @capacitor/core @capacitor/android

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Initialize Capacitor if needed
      run: |
        if [ ! -f capacitor.config.json ] && [ ! -f capacitor.config.ts ]; then
          npx cap init my-app com.example.myapp --web-dir www
        fi
        npx cap add android || true
        npx cap sync android

    - name: Final Build Check
      run: |
        if [ -d "android" ]; then
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
        else
          echo "Error: Android folder not created!"
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
